apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
spec:
  replicas: 2
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
      - name: controller
        image: mx-queretaro-1.ocir.io/ax87sp8fjwcu/borkacle-controller:1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: BOT_SERVICE_URL
          value: "http://bot-service:8080"
        - name: FRONTEND_SERVICE_URL
          value: "http://frontend-service:3000"
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: borkacle-secrets
              key: DB_URL
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: borkacle-secrets
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: borkacle-secrets
              key: DB_PASSWORD
        - name: WALLET_LOCATION
          valueFrom:
            secretKeyRef:
              name: borkacle-secrets
              key: WALLET_LOCATION
        - name: TNS_ADMIN
          value: "/app/wallet"
        - name: TRUST_STORE
          value: "/app/wallet/truststore.jks"
        - name: TRUST_STORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: borkacle-secrets
              key: TRUST_STORE_PASSWORD
        - name: KEY_STORE
          value: "/app/wallet/keystore.jks"
        - name: KEY_STORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: borkacle-secrets
              key: KEY_STORE_PASSWORD
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: borkacle-secrets
              key: TELEGRAM_BOT_TOKEN
        - name: TELEGRAM_BOT_NAME
          valueFrom:
            secretKeyRef:
              name: borkacle-secrets
              key: TELEGRAM_BOT_NAME
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: borkacle-secrets
              key: JWT_SECRET
        - name: JWT_EXPIRATION_MS
          valueFrom:
            secretKeyRef:
              name: borkacle-secrets
              key: JWT_EXPIRATION_MS
        volumeMounts:
        - name: wallet-volume
          mountPath: /app/wallet
      volumes:
      - name: wallet-volume
        persistentVolumeClaim:
          claimName: wallet-pvc
      imagePullSecrets:
      - name: ocirsecret
---
apiVersion: v1
kind: Service
metadata:
  name: controller-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
      - name: bot
        image: mx-queretaro-1.ocir.io/ax87sp8fjwcu/borkacle-bot:1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: borkacle-secrets
              key: TELEGRAM_BOT_TOKEN
        - name: TELEGRAM_BOT_NAME
          valueFrom:
            secretKeyRef:
              name: borkacle-secrets
              key: TELEGRAM_BOT_NAME
        - name: CONTROLLER_SERVICE_URL
          value: "http://controller-service:8080"
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: borkacle-secrets
              key: DB_URL
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: borkacle-secrets
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: borkacle-secrets
              key: DB_PASSWORD
        volumeMounts:
        - name: wallet-volume
          mountPath: /app/wallet
      volumes:
      - name: wallet-volume
        persistentVolumeClaim:
          claimName: wallet-pvc
      imagePullSecrets:
      - name: ocirsecret
---
apiVersion: v1
kind: Service
metadata:
  name: bot-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: bot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: mx-queretaro-1.ocir.io/ax87sp8fjwcu/borkacle-frontend:1.0.0
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: CONTROLLER_API_URL
          value: "http://controller-service:8080"
        - name: NEXT_PUBLIC_CONTROLLER_API_URL
          value: "http://controller-service:8080"
        - name: NEXT_PUBLIC_APP_URL
          value: "http://frontend-service:3000"
      imagePullSecrets:
      - name: ocirsecret
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: frontend
---
apiVersion: v1
kind: Secret
metadata:
  name: borkacle-secrets
type: Opaque
data:
  DB_URL: amRiYzpvcmFjbGU6dGhpbkBvcmFjbGVib3RfaGlnaD9UTlNfQURNSU49L2FwcC93YWxsZXQ=
  DB_USERNAME: QURNSU4=
  DB_PASSWORD: Qm9ya2FjbGUxMjMq
  WALLET_LOCATION: KFNPVVJDRT0oTUVUSE9EPWZpbGUpKE1FVEhPRF9EQVRBPShESVJFQ1RPUlk9L2FwcC93YWxsZXQpKSk=
  TRUST_STORE_PASSWORD: Qm9ya2FjbGUxMjMq
  KEY_STORE_PASSWORD: Qm9ya2FjbGUxMjMq
  TELEGRAM_BOT_TOKEN: NzU1MzcwNTg4MDpBQUVUeXBSX3hrZUY0enF0SWNVS3VoVWZ4RFFMOGtzajdB
  TELEGRAM_BOT_NAME: Ym9ya2FjbGVfYm90
  JWT_SECRET: Ym9ya2FjbGVTZWNyZXRLZXkyMDI0Rm9ySldUVG9rZW5HZW5lcmF0aW9uQW5kVmFsaWRhdGlvbg==
  JWT_EXPIRATION_MS: ODY0MDAwMDA=
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallet-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi