apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: borkacle
data:
  SERVER_PORT: "8080"
  BOT_SERVICE_URL: "http://bot:8080"
  FRONTEND_SERVICE_URL: "http://frontend"
  NODE_ENV: "production"
  CONTROLLER_SERVICE_URL: "http://controller:8080"
  NEXT_PUBLIC_CONTROLLER_API_URL: "/api/proxy"
  NEXT_PUBLIC_APP_URL: "http://frontend"
  WALLET_LOCATION: "/app/wallet"
  TNS_ADMIN: "/app/wallet"
  TRUST_STORE: "/app/wallet/truststore.jks"
  KEY_STORE: "/app/wallet/keystore.jks"
  oracle.net.wallet_location: "/app/wallet"