apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot
  namespace: borkacle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
        - name: bot
          image: mx-queretaro-1.ocir.io/axtwc9mqbq4b/borkacle-bot:${VERSION}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          volumeMounts:
            - name: wallet-volume
              mountPath: /app/wallet
      volumes:
        - name: wallet-volume
          secret:
            secretName: wallet-secret
            