apiVersion: v1
kind: Service
metadata:
  name: bot
  namespace: borkacle
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
spec:
  type: LoadBalancer
  selector:
    app: bot
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
