apiVersion: v1
kind: Service
metadata:
  name: controller
  namespace: borkacle
spec:
  type: ClusterIP
  selector:
    app: controller
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
