apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: borkacle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
        - name: controller
          image: ${CONTROLLER_IMAGE}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          volumeMounts:
            - name: wallet-volume
              mountPath: /app/wallet
      volumes:
        - name: wallet-volume
          secret:
            secretName: wallet-secret
            