apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: borkacle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: mx-queretaro-1.ocir.io/axtwc9mqbq4b/borkacle-frontend:${VERSION}
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
