name: Borkacle CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      
      - name: Check Java format
        run: |
          cd MtdrSpring/backend
          mkdir -p tools
          wget -q https://github.com/google/google-java-format/releases/download/v1.15.0/google-java-format-1.15.0-all-deps.jar -O tools/formatter.jar
          find src -name "*.java" -type f | xargs java -jar tools/formatter.jar --dry-run
      
      - name: Run Checkstyle
        # Ignore errors "|| true" and continue the workflow
        run: |
          cd MtdrSpring/backend
          mkdir -p tools
          wget -q https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.3.3/checkstyle-10.3.3-all.jar -O tools/checkstyle.jar
          java -jar tools/checkstyle.jar -c sun_checks.xml src/main/java || true
      
      - name: Test Backend
        run: |
          cd MtdrSpring/backend
          if find src/test/java -name "*Test.java" -type f | grep -q .; then
            echo "Ejecutando pruebas de backend..."
            ./mvnw test
          else
            echo "No se encontraron archivos de test Java, saltando pruebas de backend"
          fi
      
      - name: Build Backend
        run: cd MtdrSpring/backend && ./mvnw clean package -DskipTests
      
      - name: Build Docker image
        run: |
          cd MtdrSpring/backend
          docker build -t borkacle-backend:${{ github.sha }} .
      
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: MtdrSpring/backend/src/main/frontend/package-lock.json
      
      - name: Install dependencies
        run: cd MtdrSpring/backend/src/main/frontend && npm ci
      
      - name: Install dev dependencies
        run: cd MtdrSpring/backend/src/main/frontend && npm install --save-dev prettier @biomejs/biome
      
      - name: Check formatting
        run: cd MtdrSpring/backend/src/main/frontend && npx prettier --check . || true
      
        # Ignore errors "|| true" and continue the workflow
      - name: Lint
        run: cd MtdrSpring/backend/src/main/frontend && npx biome check . || true
      
      - name: Test Frontend
        run: |
          cd MtdrSpring/backend/src/main/frontend
          if grep -q "\"test\":" package.json; then
            echo "Ejecutando pruebas de frontend..."
            npm test -- --run || npm test
          else
            echo "No se encontraron scripts de test en package.json, saltando pruebas de frontend"
          fi
      
      - name: Build frontend
        run: cd MtdrSpring/backend/src/main/frontend && npm run build 